apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-analytics
  labels:
    app: analytics
    {{- include "example-branch.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.analytics.replicas }}
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      {{- if .Values.analytics.compute }}
      nodeSelector:
        kindling.dev/compute: {{ .Values.analytics.compute | quote }}
      tolerations:
      - key: kindling.dev/compute
        operator: Equal
        value: {{ .Values.analytics.compute | quote }}
        effect: NoSchedule
      {{- end }}
      containers:
      - name: analytics
        image: {{ .Values.analytics.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.analytics.port }}
        env:
        {{- if .Values.analytics.env.REDIS_URL }}
        - name: REDIS_URL
          value: {{ .Values.analytics.env.REDIS_URL | quote }}
        {{- end }}
        {{- if .Values.analytics.env.APP_SECRET_KEY }}
        - name: APP_SECRET_KEY
          value: {{ .Values.analytics.env.APP_SECRET_KEY | quote }}
        {{- end }}
        {{- if .Values.analytics.env.LAB_THINGY_JWT_SECRET }}
        - name: LAB_THINGY_JWT_SECRET
          value: {{ .Values.analytics.env.LAB_THINGY_JWT_SECRET | quote }}
        {{- end }}
        - name: MONGO_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-analytics-secrets
              key: MONGO_HOST
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-analytics-secrets
              key: MONGO_USER
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-analytics-secrets
              key: MONGO_PASSWORD
