apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-secrets
  labels:
    app: auth
    {{- include "example-branch.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTH0_DOMAIN: {{ .Values.auth.secrets.AUTH0_DOMAIN | quote }}
  AUTH0_CLIENT_ID: {{ .Values.auth.secrets.AUTH0_CLIENT_ID | quote }}
  AUTH0_CLIENT_SECRET: {{ .Values.auth.secrets.AUTH0_CLIENT_SECRET | quote }}
  MONGO_HOST: {{ .Values.auth.secrets.MONGO_HOST | quote }}
  MONGO_USER: {{ .Values.auth.secrets.MONGO_USER | quote }}
  MONGO_PASSWORD: {{ .Values.auth.secrets.MONGO_PASSWORD | quote }}
