apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    app: auth
    {{- include "example-branch.labels" . | nindent 4 }}
spec:
  selector:
    app: auth
  ports:
  - port: {{ .Values.auth.port }}
    targetPort: {{ .Values.auth.port }}
    protocol: TCP
