apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-billing-secrets
  labels:
    app: billing
    {{- include "example-branch.labels" . | nindent 4 }}
type: Opaque
stringData:
  STRIPE_API_KEY: {{ .Values.billing.secrets.STRIPE_API_KEY | quote }}
  MONGO_HOST: {{ .Values.billing.secrets.MONGO_HOST | quote }}
  MONGO_USER: {{ .Values.billing.secrets.MONGO_USER | quote }}
  MONGO_PASSWORD: {{ .Values.billing.secrets.MONGO_PASSWORD | quote }}
