apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-garbage-collection
  labels:
    app: garbage-collection
    {{- include "example-branch.labels" . | nindent 4 }}
spec:
  selector:
    app: garbage-collection
  ports:
  - port: {{ .Values.garbage_collection.port }}
    targetPort: {{ .Values.garbage_collection.port }}
    protocol: TCP
