apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-labs-secrets
  labels:
    app: labs
    {{- include "example-branch.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_HOST: {{ .Values.labs.secrets.MONGO_HOST | quote }}
  MONGO_USER: {{ .Values.labs.secrets.MONGO_USER | quote }}
  MONGO_PASSWORD: {{ .Values.labs.secrets.MONGO_PASSWORD | quote }}
