apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-labs
  labels:
    app: labs
    {{- include "example-branch.labels" . | nindent 4 }}
spec:
  selector:
    app: labs
  ports:
  - port: {{ .Values.labs.port }}
    targetPort: {{ .Values.labs.port }}
    protocol: TCP
