apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-llm-proxy-secrets
  labels:
    app: llm-proxy
    {{- include "example-branch.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_HOST: {{ .Values.llm_proxy.secrets.MONGO_HOST | quote }}
  MONGO_USER: {{ .Values.llm_proxy.secrets.MONGO_USER | quote }}
  MONGO_PASSWORD: {{ .Values.llm_proxy.secrets.MONGO_PASSWORD | quote }}
