apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-orgs
  labels:
    app: orgs
    {{- include "example-branch.labels" . | nindent 4 }}
spec:
  selector:
    app: orgs
  ports:
  - port: {{ .Values.orgs.port }}
    targetPort: {{ .Values.orgs.port }}
    protocol: TCP
