apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rag-ingest
  labels:
    app: rag-ingest
    {{- include "example-branch.labels" . | nindent 4 }}
spec:
  selector:
    app: rag-ingest
  ports:
  - port: {{ .Values.rag_ingest.port }}
    targetPort: {{ .Values.rag_ingest.port }}
    protocol: TCP
