apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rag-ingest-secrets
  labels:
    app: rag-ingest
    {{- include "example-branch.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_HOST: {{ .Values.rag_ingest.secrets.MONGO_HOST | quote }}
  MONGO_USER: {{ .Values.rag_ingest.secrets.MONGO_USER | quote }}
  MONGO_PASSWORD: {{ .Values.rag_ingest.secrets.MONGO_PASSWORD | quote }}
