apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-video
  labels:
    app: video
    {{- include "example-branch.labels" . | nindent 4 }}
spec:
  selector:
    app: video
  ports:
  - port: {{ .Values.video.port }}
    targetPort: {{ .Values.video.port }}
    protocol: TCP
