apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-video-secrets
  labels:
    app: video
    {{- include "example-branch.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_HOST: {{ .Values.video.secrets.MONGO_HOST | quote }}
  MONGO_USER: {{ .Values.video.secrets.MONGO_USER | quote }}
  MONGO_PASSWORD: {{ .Values.video.secrets.MONGO_PASSWORD | quote }}
