apiVersion: apps/v1
kind: Deployment
metadata:
  name: embed-cdn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embed-cdn
  template:
    metadata:
      labels:
        app: embed-cdn
    spec:
      containers:
      - name: nginx
        image: {{ .Values.cdn.containers.image | quote }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: embed-cdn
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: embed-cdn
  type: ClusterIP
