apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: compute-api
      labels:
        app: compute-api
    spec:
      selector:
        matchLabels:
          app: compute-api
      replicas: 1
      template:
        metadata:
          labels:
            app: compute-api
        spec:
          containers:
            - name: compute-api
              image: {{ .Values.computeAPI.containers.image }}
              imagePullPolicy: Always
              securityContext:
                # runAsNonRoot: true
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
              envFrom:
                - secretRef:
                    name: lab-thingy-jwt-secret
              ports:
                - name: http
                  containerPort: 8000
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /healthz
                  port: http
                initialDelaySeconds: 3
                periodSeconds: 10
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: http
                initialDelaySeconds: 10
                periodSeconds: 20
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 200m
                  memory: 512Mi
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
          volumes:
            - name: tmp
              emptyDir: {}
  - apiVersion: v1
    kind: Service
    metadata:
      name: compute-api
      labels:
        app: compute-api
    spec:
      ports:
        - port: 8000
          targetPort: 8000
          name: http
      selector:
        app: compute-api
      type: ClusterIP

  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: compute-api-monitor
      labels:
        release: kube-prometheus
    spec:
      selector:
        matchLabels:
          app: compute-api
      endpoints:
        - port: http
          path: /metrics
          interval: 15s
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: compute-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: compute-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70