apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: docs
      labels:
        api: docs
    spec:
      selector:
        matchLabels:
          api: docs
      replicas: 1
      template:
        metadata:
          labels:
            api: docs
        spec:
          containers:
            - name: docs
              image: {{ .Values.docs.containers.image }}
              imagePullPolicy: Always
              ports:
                - name: docs
                  containerPort: 80
                  protocol: TCP
  - apiVersion: v1
    kind: Service
    metadata:
      name: docs
    spec:
      ports:
        - port: 80
          targetPort: 80
          name: docs
      selector:
        api: docs
      type: ClusterIP
